
version: '3.7'
services:
    postgres:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          # copy the sql script to create tables
          - ./db/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
          - .